project:
  name: chess_ai
  seed: 42

wandb:
  project: chess_ai
  enabled: true

hardware:
  workers: 6
  pin_memory: true
  prefetch: 4
  mixed_precision: true
  prod:
    workers: 16
    pin_memory: true
    prefetch: 8
    mixed_precision: true

model:
  channels: 32
  blocks: 4
  attention: true
  prod:
    channels: 128
    blocks: 12
    attention: true

data:
  batch: 128
  dataset: data/dataset.h5
  train_idx: data/train_indices.npy
  val_idx: data/val_indices.npy
  test_idx: data/test_indices.npy
  raw_pgn: data/lichess_db_standard_rated_2025-03.pgn
  max_games: 10
  min_elo: 1500
  max_elo: 3500
  prod:
    batch: 4096
    max_games: 2000000
    min_elo: 2200

training:
  checkpoint_interval: 1
  prod:
    checkpoint_interval: 5

supervised:
  epochs: 2
  lr: 0.005
  weight_decay: 0.0001
  optimizer: adam
  scheduler: linear
  accum_steps: 1
  policy_weight: 1.0
  value_weight: 1.0
  grad_clip: 5.0
  momentum: 0.9
  early_stop: true
  patience: 2
  min_accuracy_threshold: 0.001
  prod:
    epochs: 200
    lr: 0.0001
    weight_decay: 0.00001
    optimizer: adamw
    scheduler: onecycle
    accum_steps: 2
    policy_weight: 1.0
    value_weight: 1.0
    grad_clip: 1.0
    momentum: 0.9
    early_stop: true
    patience: 15
    min_accuracy_threshold: 0.2

reinforcement:
  iters: 2
  games_per_iter: 4
  sims_per_move: 20
  epochs_per_iter: 2
  c_puct: 1.4
  temp: 0.5
  threads: 6
  prod:
    iters: 100
    games_per_iter: 5000
    sims_per_move: 2000
    epochs_per_iter: 12
    c_puct: 1.0
    temp: 0.2
    threads: 64

eval:
  max_samples: 200
  visualize_moves: true
  sl_vs_rl: true
  prod:
    max_samples: 100000
    visualize_moves: true
    sl_vs_rl: true

benchmark:
  games: 4
  mcts: true
  opening_book: true
  switch_colors: true
  stockfish_path: engines/stockfish-ubuntu-x86-64-avx2
  stockfish_elo: 1200
  stockfish_time: 0.05
  stockfish_depth: null
  prod:
    games: 1000
    stockfish_elo: 2800
    stockfish_time: 2.0
    stockfish_depth: 20

hyperopt:
  trials: 5
  timeout: 3600
  jobs: 2
  lr_range: [0.0005, 0.01]
  wd_range: [0.00005, 0.001]
  batch_sizes: [64, 128, 256]
  epochs_range: [1, 3]
  optimizers: ["adam", "adamw"]
  schedulers: ["linear", "onecycle"]
  prod:
    trials: 300
    timeout: 1209600
    jobs: 16
    lr_range: [0.0000001, 0.01]
    wd_range: [0.00000001, 0.001]
    batch_sizes: [256, 512, 1024, 2048, 4096, 8192]
    epochs_range: [50, 300]
    optimizers: ["adam", "adamw", "sgd", "rmsprop"]
    schedulers: ["linear", "step", "cosine", "onecycle"]

paths:
  drive_root: chess_ai
  models: models
  data: data
  logs: logs