project:
  name: chess_ai
  seed: 42

wandb:
  project: chess_ai
  enabled: true

hardware:
  tpu: false
  workers: 2
  pin_memory: true
  prefetch: 2
  mixed_precision: true
  prod:
    tpu: true
    workers: 8
    prefetch: 4

model:
  channels: 32
  blocks: 3
  attention: true
  prod:
    channels: 96
    blocks: 6

data:
  batch: 128
  dataset: data/dataset.h5
  train_idx: data/train_indices.npy
  val_idx: data/val_indices.npy
  test_idx: data/test_indices.npy
  raw_pgn: data/lichess_db_standard_rated_2025-03.pgn
  max_games: 10
  min_elo: 1600
  max_elo: 3000
  prod:
    batch: 512
    dataset: data/dataset.h5
    train_idx: data/train_indices.npy
    val_idx: data/val_indices.npy
    test_idx: data/test_indices.npy
    raw_pgn: data/lichess_db_standard_rated_2025-03.pgn
    max_games: 500000
    min_elo: 2000

training:
  checkpoint_interval: 1
  prod:
    checkpoint_interval: 5

supervised:
  epochs: 2
  lr: 0.001
  weight_decay: 0.0001
  optimizer: adamw
  scheduler: onecycle
  accum_steps: 2
  policy_weight: 1.0
  value_weight: 1.0
  grad_clip: 1.0
  momentum: 0.9
  early_stop: true
  patience: 3
  prod:
    epochs: 50
    lr: 0.0005
    accum_steps: 4
    patience: 7

reinforcement:
  iters: 2
  games_per_iter: 5
  sims_per_move: 100
  epochs_per_iter: 2
  c_puct: 1.4
  temp: 0.5
  threads: 2
  prod:
    iters: 20
    games_per_iter: 1000
    sims_per_move: 800
    epochs_per_iter: 10
    threads: 16

eval:
  max_samples: 1000
  prod:
    max_samples: 10000

hyperopt:
  trials: 2
  timeout: 3600
  jobs: 1
  lr_range: [0.0001, 0.01]
  wd_range: [0.00001, 0.001]
  batch_sizes: [64, 128]
  epochs_range: [2, 3]
  optimizers: ["adam", "adamw"]
  schedulers: ["linear", "step"]
  prod:
    trials: 100
    timeout: 172800
    jobs: 4
    lr_range: [0.00001, 0.01]
    wd_range: [0.000001, 0.001]
    batch_sizes: [128, 256, 512, 1024]
    epochs_range: [15, 40]
    optimizers: ["adam", "adamw", "sgd", "rmsprop"]
    schedulers: ["linear", "step", "cosine", "onecycle"]

benchmark:
  games: 10
  mcts: true
  opening_book: true
  stockfish_path: engines/stockfish-ubuntu-x86-64-avx2
  stockfish_elo: 1500
  stockfish_time: 0.1
  stockfish_depth: null
  prod:
    games: 200
    stockfish_elo: 2000
    stockfish_time: 0.5

paths:
  drive_root: chess_ai
  models: models
  data: data
  logs: logs