project:
  name: chess_ai
  seed: 42

wandb:
  project: chess_ai
  enabled: true

hardware:
  workers: 2
  pin_memory: true
  prefetch: 4
  mixed_precision: true
  prod:
    workers: 8
    pin_memory: true
    prefetch: 8
    mixed_precision: true

model:
  channels: 32
  blocks: 2
  attention: false
  prod:
    channels: 48
    blocks: 3
    attention: true

data:
  batch: 256
  dataset: data/dataset.h5
  train_idx: data/train_indices.npy
  val_idx: data/val_indices.npy
  test_idx: data/test_indices.npy
  raw_pgn: data/lichess_db_standard_rated_2025-03.pgn
  augment_flip: true
  max_games: 10
  min_elo: 1500
  max_elo: 3500
  prod:
    batch: 512
    max_games: 25000
    min_elo: 1800

supervised:
  epochs: 2
  lr: 0.005
  weight_decay: 0.0001
  optimizer: adam
  scheduler: linear
  accum_steps: 2
  policy_weight: 1.0
  value_weight: 1.0
  grad_clip: 5.0
  momentum: 0.9
  early_stop: true
  patience: 2
  min_accuracy_threshold: 0.001
  prod:
    epochs: 4
    lr: 0.002
    weight_decay: 0.00005
    optimizer: adamw
    scheduler: onecycle
    accum_steps: 8
    policy_weight: 1.0
    value_weight: 1.0
    grad_clip: 1.0
    momentum: 0.9
    early_stop: true
    patience: 1
    min_accuracy_threshold: 0.05

reinforcement:
  iters: 1
  games_per_iter: 4
  sims_per_move: 10
  epochs_per_iter: 1
  c_puct: 1.4
  temp: 0.5
  threads: 6
  prod:
    iters: 5
    games_per_iter: 50
    sims_per_move: 100
    epochs_per_iter: 2
    c_puct: 1.6
    temp: 0.35
    threads: 10

eval:
  max_samples: 200
  visualize_moves: true
  sl_vs_rl: true
  prod:
    max_samples: 400
    visualize_moves: true
    sl_vs_rl: true

benchmark:
  games: 2
  mcts: true
  opening_book: true
  switch_colors: true
  stockfish_path: stockfish
  stockfish_elo: 1200
  stockfish_time: 0.05
  stockfish_depth: null
  prod:
    games: 8
    mcts: true
    opening_book: true
    switch_colors: true
    stockfish_path: stockfish
    stockfish_elo: 1600
    stockfish_time: 0.1
    stockfish_depth: 6

paths:
  drive_root: chess_ai
  models: models
  data: data
  logs: logs