project:
  name: chess_ai
  seed: 42

wandb:
  project: chess_ai
  enabled: true

hardware:
  workers: 2
  pin_memory: true
  prefetch: 4
  mixed_precision: true
  prod:
    workers: 4
    pin_memory: true
    prefetch: 4
    mixed_precision: true

model:
  channels: 32
  blocks: 4
  attention: true
  prod:
    channels: 64
    blocks: 5
    attention: true

data:
  batch: 128
  dataset: data/dataset.h5
  train_idx: data/train_indices.npy
  val_idx: data/val_indices.npy
  test_idx: data/test_indices.npy
  raw_pgn: data/lichess_db_standard_rated_2025-03.pgn
  augment_flip: true
  max_games: 10
  min_elo: 1500
  max_elo: 3500
  prod:
    batch: 2048
    max_games: 300000
    min_elo: 1800

training:
  checkpoint_interval: 1
  prod:
    checkpoint_interval: 3

supervised:
  epochs: 2
  lr: 0.005
  weight_decay: 0.0001
  optimizer: adam
  scheduler: linear
  accum_steps: 1
  policy_weight: 1.0
  value_weight: 1.0
  grad_clip: 5.0
  momentum: 0.9
  early_stop: true
  patience: 2
  min_accuracy_threshold: 0.001
  prod:
    epochs: 6
    lr: 0.001
    weight_decay: 0.00005
    optimizer: adamw
    scheduler: onecycle
    accum_steps: 4
    policy_weight: 1.0
    value_weight: 1.0
    grad_clip: 1.0
    momentum: 0.9
    early_stop: true
    patience: 2
    min_accuracy_threshold: 0.05

reinforcement:
  iters: 2
  games_per_iter: 4
  sims_per_move: 20
  epochs_per_iter: 2
  c_puct: 1.4
  temp: 0.5
  threads: 6
  prod:
    iters: 4
    games_per_iter: 50
    sims_per_move: 120
    epochs_per_iter: 2
    c_puct: 1.2
    temp: 0.3
    threads: 4

eval:
  max_samples: 200
  visualize_moves: true
  sl_vs_rl: true
  prod:
    max_samples: 400
    visualize_moves: true
    sl_vs_rl: true

benchmark:
  games: 4
  mcts: true
  opening_book: true
  switch_colors: true
  stockfish_path: stockfish
  stockfish_elo: 1200
  stockfish_time: 0.05
  stockfish_depth: null
  prod:
    games: 16
    mcts: true
    opening_book: true
    switch_colors: true
    stockfish_path: stockfish
    stockfish_elo: 1800
    stockfish_time: 0.15
    stockfish_depth: 8

hyperopt:
  trials: 2
  timeout: 3600
  jobs: 2
  lr_range: [0.0005, 0.01]
  wd_range: [0.00005, 0.001]
  batch_sizes: [64, 128, 256]
  epochs_range: [1, 3]
  optimizers: ["adam", "adamw"]
  schedulers: ["linear", "onecycle"]
  prod:
    trials: 5
    timeout: 1500
    jobs: 5
    lr_range: [0.0001, 0.001]
    wd_range: [0.00001, 0.0001]
    batch_sizes: [256, 512]
    epochs_range: [4, 8]
    optimizers: ["adamw"]
    schedulers: ["onecycle"]

paths:
  drive_root: chess_ai
  models: models
  data: data
  logs: logs