project:
  name: chess_ai
  seed: 42

wandb:
  project: chess_ai
  enabled: true

hardware:
  workers: 2
  pin_memory: true
  prefetch: 2
  mixed_precision: true
  prod:
    workers: 8
    pin_memory: true
    prefetch: 4
    mixed_precision: true

model:
  channels: 16
  blocks: 2
  attention: false
  prod:
    channels: 64
    blocks: 8
    attention: true

data:
  batch: 64
  dataset: data/dataset.h5
  train_idx: data/train_indices.npy
  val_idx: data/val_indices.npy
  test_idx: data/test_indices.npy
  raw_pgn: data/lichess_db_standard_rated_2025-03.pgn
  max_games: 5
  min_elo: 1500
  max_elo: 3500
  prod:
    batch: 2048
    max_games: 1000000
    min_elo: 2200

training:
  checkpoint_interval: 1
  prod:
    checkpoint_interval: 5

supervised:
  epochs: 1
  lr: 0.005
  weight_decay: 0.0001
  optimizer: adam
  scheduler: linear
  accum_steps: 1
  policy_weight: 1.0
  value_weight: 1.0
  grad_clip: 5.0
  momentum: 0.9
  early_stop: true
  patience: 2
  min_accuracy_threshold: 0.001
  prod:
    epochs: 120
    lr: 0.0002
    weight_decay: 0.00005
    optimizer: adamw
    scheduler: onecycle
    accum_steps: 4
    policy_weight: 1.0
    value_weight: 1.0
    grad_clip: 1.0
    momentum: 0.9
    early_stop: true
    patience: 10
    min_accuracy_threshold: 0.2

reinforcement:
  iters: 1
  games_per_iter: 2
  sims_per_move: 10
  epochs_per_iter: 1
  c_puct: 1.4
  temp: 0.5
  threads: 2
  prod:
    iters: 75
    games_per_iter: 2500
    sims_per_move: 1200
    epochs_per_iter: 8
    c_puct: 1.0
    temp: 0.2
    threads: 32

eval:
  max_samples: 100
  visualize_moves: true
  sl_vs_rl: true
  prod:
    max_samples: 50000
    visualize_moves: true
    sl_vs_rl: true

benchmark:
  games: 2
  mcts: true
  opening_book: true
  switch_colors: true
  stockfish_path: engines/stockfish-ubuntu-x86-64-avx2
  stockfish_elo: 1200
  stockfish_time: 0.05
  stockfish_depth: null
  prod:
    games: 500
    stockfish_elo: 2500
    stockfish_time: 1.0
    stockfish_depth: 15

hyperopt:
  trials: 2
  timeout: 1800
  jobs: 1
  lr_range: [0.001, 0.01]
  wd_range: [0.0001, 0.001]
  batch_sizes: [32, 64]
  epochs_range: [1, 2]
  optimizers: ["adam"]
  schedulers: ["linear"]
  prod:
    trials: 200
    timeout: 604800
    jobs: 8
    lr_range: [0.000001, 0.01]
    wd_range: [0.0000001, 0.001]
    batch_sizes: [128, 256, 512, 1024, 2048, 4096]
    epochs_range: [30, 200]
    optimizers: ["adam", "adamw", "sgd", "rmsprop"]
    schedulers: ["linear", "step", "cosine", "onecycle"]

paths:
  drive_root: chess_ai
  models: models
  data: data
  logs: logs