name: hybrid_chess_ai
channels:
  - nvidia
  - pytorch
  - conda-forge
dependencies:
  - python=3.11
  - pytorch=2.5.1
  - pytorch-cuda=12.4
  - numpy
  - chess
  - h5py
  - streamlit
  - wandb
  - click=8.1.3
  - optuna
  - scikit-learn
  - matplotlib
  - shap
  - pip
  - pip:
      - berserk