name: hybrid_chess_ai
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy
  - torch
  - torchvision
  - scikit-learn
  - matplotlib
  - pyqt
  - chess
  - h5py
  - tqdm
  - networkx