name: hybrid_chess_ai
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - numpy
  - pandas
  - pytorch
  - torchvision
  - scikit-learn
  - matplotlib
  - pyqt
  - chess
  - tqdm
  - pyyaml
  - flask
  - notebook
  - matplotlib
  - pytest
  - sphinx