[tool.ruff]
line-length = 110
target-version = "py313"
src = ["python"]
extend-exclude = [
    ".venv",
    "build",
    "dist",
    "logs",
    "checkpoints",
]

[tool.ruff.lint]
select = [
    "E",
    "F",
    "I",
    "UP",
    "B",
    "SIM",
    "C4",
    "RUF",
]
ignore = [
    "E203",
    "E501",
]

[tool.ruff.lint.isort]
combine-as-imports = true
known-first-party = ["arena", "self_play", "train", "pipeline"]

[tool.ruff.lint.per-file-ignores]
"python/__init__.py" = ["F401"]
"python/pipeline/__init__.py" = ["F401"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-format = true
