## Reproducibility
# Set SEED = 0 to disable strict reproducibility and allow fastest settings.
SEED = 0

## Torch / AMP / performance
AMP_ENABLED = True
AMP_PREFER_BFLOAT16 = True
TORCH_ALLOW_TF32 = True
TORCH_COMPILE = True
TORCH_COMPILE_MODE = "max-autotune"
TORCH_COMPILE_FULLGRAPH = True
TORCH_COMPILE_DYNAMIC = False
TORCH_CUDNN_BENCHMARK = True
TORCH_THREADS_INTRA = 1
TORCH_THREADS_INTER = 1
TORCH_MATMUL_FLOAT32_PRECISION = "high"
MODEL_CHANNELS_LAST = True
EVAL_MODEL_CHANNELS_LAST = True
TRAIN_PIN_MEMORY = False
EVAL_PIN_MEMORY = False

## Logging / IO
LOG_TO_FILE = True
LOG_FILE_PATH = "log.txt"
LOG_LEVEL = "INFO"
CUDA_EMPTY_CACHE_EVERY_ITERS = 120
OPENINGS_FILE_PATH = "openings.txt"
CHECKPOINT_SAVE_EVERY_ITERS = 30
CHECKPOINT_FILE_PATH = "checkpoint.pt"
BEST_MODEL_FILE_PATH = "best_model.pt"

## Board encoding / shapes
BOARD_SIZE = 8
NSQUARES = BOARD_SIZE * BOARD_SIZE
PLANES_PER_POSITION = 14
HISTORY_LENGTH = 8
INPUT_PLANES = HISTORY_LENGTH * PLANES_PER_POSITION + 7
POLICY_PLANES = 73
POLICY_OUTPUT = POLICY_PLANES * NSQUARES
NUM_DIRECTIONS = 8
DIR_MAX_DIST = 7
NUM_KNIGHT_DIRS = 8
KNIGHT_PLANES_BASE = 56
PROMO_CHOICES = 3
PROMO_STRIDE = 3
DIR_MAP_MIRROR = [2, 1, 0, 4, 3, 7, 6, 5]
KMAP_MIRROR = [1, 0, 3, 2, 5, 4, 7, 6]
DIR_MAP_ROT180 = [7, 6, 5, 4, 3, 2, 1, 0]
KMAP_ROT180 = [7, 6, 5, 4, 3, 2, 1, 0]
DIR_MAP_VFLIP_CS = [5, 6, 7, 3, 4, 0, 1, 2]
KMAP_VFLIP_CS = [6, 7, 4, 5, 2, 3, 0, 1]
PMAP_PROMOS = [0, 2, 1]
U8_SCALE = 255.0
VALUE_I8_SCALE = 127.0

## Model architecture
MODEL_BLOCKS = 12
MODEL_CHANNELS = 224
MODEL_VALUE_CONV_CHANNELS = 16
MODEL_VALUE_HIDDEN_DIM = 1024

## Evaluator (inference) batching/cache
EVAL_BATCH_SIZE_MAX = 8192
EVAL_BATCH_COALESCE_MS = 22
EVAL_CACHE_CAPACITY = 40_000
EVAL_WORKER_JOIN_TIMEOUT_S = 0.15
EVAL_CACHE_USE_FP16 = True

## Self-play / replay buffer
REPLAY_BUFFER_CAPACITY = 150_000
SELFPLAY_NUM_WORKERS = 32
GAME_MAX_PLIES = 320
SELFPLAY_TEMP_MOVES = 45
SELFPLAY_TEMP_HIGH = 0.90
SELFPLAY_TEMP_LOW = 0.07
SELFPLAY_DETERMINISTIC_TEMP_EPS = 0.005
SELFPLAY_OPENING_RANDOM_PLIES_MAX = 6

## MCTS settings (training)
MCTS_TRAIN_SIMULATIONS_BASE = 512
MCTS_TRAIN_SIMULATIONS_MIN = 128
MCTS_TRAIN_SIM_DECAY_MOVE_INTERVAL = 12
MCTS_C_PUCT = 1.35
MCTS_C_PUCT_BASE = 19652.0
MCTS_C_PUCT_INIT = 1.55
MCTS_DIRICHLET_ALPHA = 0.30
MCTS_DIRICHLET_WEIGHT = 0.25
MCTS_FPU_REDUCTION = 0.12
MCTS_VISIT_COUNT_CLAMP = 65535

## Resignation rules
RESIGN_VALUE_THRESHOLD = -0.85
RESIGN_CONSECUTIVE_PLIES = 3
RESIGN_CONSECUTIVE_MIN = 3
RESIGN_PLAYTHROUGH_FRACTION = 0.33

## Sampling / augmentation
REPLAY_SNAPSHOT_RECENT_WINDOW_FRAC = 0.15
REPLAY_SNAPSHOT_RECENT_RATIO_DEFAULT = 0.6
TRAIN_RECENT_SAMPLE_RATIO = 0.75
AUGMENT_MIRROR_PROB = 0.5
AUGMENT_ROT180_PROB = 0.25
AUGMENT_VFLIP_CS_PROB = 0.25

## Optimization
TRAIN_BATCH_SIZE = 10240
TRAIN_LR_INIT = 3.4e-3
TRAIN_LR_WARMUP_STEPS = 800
TRAIN_LR_FINAL = 6.5e-4
TRAIN_WEIGHT_DECAY = 1e-4
TRAIN_MOMENTUM = 0.9
TRAIN_GRAD_CLIP_NORM = 0.80
LOSS_POLICY_WEIGHT = 1.0
LOSS_VALUE_WEIGHT = 0.8
LOSS_VALUE_WEIGHT_LATE = 1.0
LOSS_VALUE_WEIGHT_SWITCH_ITER = 30
LOSS_POLICY_LABEL_SMOOTH = 0.03
LOSS_ENTROPY_COEF_INIT = 1.0e-4
LOSS_ENTROPY_ANNEAL_ITERS = 60
LOSS_ENTROPY_COEF_MIN = 4.0e-05
EMA_ENABLED = True
EMA_DECAY = 0.999

## Schedule / iteration
TRAIN_TOTAL_ITERATIONS = 168
SELFPLAY_GAMES_PER_ITER = 360
TRAIN_LR_SCHED_STEPS_PER_ITER_EST = 36
TRAIN_LR_SCHED_DRIFT_ADJUST_THRESHOLD = 15.0
TRAIN_TARGET_TRAIN_SAMPLES_PER_NEW = 6.0
TRAIN_UPDATE_STEPS_MIN = 32
TRAIN_UPDATE_STEPS_MAX = 1024

## Arena evaluation (gating)
MCTS_EVAL_SIMULATIONS = 384
ARENA_EVAL_EVERY_ITERS = 8
ARENA_EVAL_CACHE_CAPACITY = 32_768
ARENA_GAMES_PER_EVAL = 120
ARENA_TEMPERATURE = 0.05
ARENA_TEMP_MOVES = 8
ARENA_DIRICHLET_WEIGHT = 0.0
ARENA_OPENING_TEMPERATURE_EPS = 1e-6
ARENA_DETERMINISTIC = False
ARENA_STRATIFY_OPENINGS = True
ARENA_DRAW_SCORE = 0.48
ARENA_GATE_DRAW_WEIGHT = 0.48
ARENA_GATE_BASELINE_P = 0.5
ARENA_GATE_Z_EARLY = 1.64
ARENA_GATE_Z_LATE = 2.05
ARENA_GATE_Z_SWITCH_ITER = 200
ARENA_GATE_MIN_GAMES = 180
ARENA_GATE_DECISIVE_SECONDARY = True
ARENA_GATE_MIN_DECISIVES = 100
ARENA_CANDIDATE_MAX_ROUNDS = 4
ARENA_CANDIDATE_MAX_GAMES = 600
ARENA_PAIRING_FACTOR = 2
ARENA_GATE_EPS = 1e-9

## Dynamic RAM/cache/buffer tuning
# Enable/disable automatic host RAM-aware tuning during training.
DYN_TUNE_RAM_ENABLED = True
# Trigger thresholds based on system RAM usage percentage.
DYN_RAM_LOW_PCT = 55.0
DYN_RAM_HIGH_PCT = 82.0
# Cooldown in iterations between tuning adjustments.
DYN_TUNE_COOLDOWN_ITERS = 2
# Replay buffer dynamic bounds and step size.
DYN_REPLAY_MIN = 80_000
DYN_REPLAY_MAX = 300_000
DYN_REPLAY_STEP = 10_000
# Evaluator cache bounds and step size.
DYN_EVAL_MIN = 8_192
DYN_EVAL_MAX = 200_000
DYN_EVAL_STEP = 4_096
# Arena evaluator cache bounds/steps (separate from main evaluator).
DYN_ARENA_EVAL_MIN = 8_192
DYN_ARENA_EVAL_MAX = 131_072
DYN_ARENA_EVAL_STEP = 4_096
