# Tuned for Ryzen 7 5800H (8C/16T), Laptop RTX 3070 8GB, 16GB RAM.

MODEL:
  blocks: 7
  channels: 96

TORCH:
  threads_intra: 10
  threads_inter: 2
  amp_enabled: true
  model_channels_last: true
  eval_model_channels_last: true
  matmul_float32_precision: high
  cuda_matmul_fp32_precision: tf32
  cudnn_conv_fp32_precision: tf32
  cuda_allow_fp16_reduced_reduction: true
  cudnn_benchmark: true
  deterministic: false

EVAL:
  batch_size_max: 192
  coalesce_ms: 2
  cache_capacity: 8000
  value_cache_capacity: 12000
  encode_cache_capacity: 4000
  use_fp16_cache: true

SELFPLAY:
  num_workers: 6
  game_max_plies: 160
  temperature_moves: 20
  temperature_high: 1.15
  temperature_low: 0.25
  deterministic_temp_eps: 0.002
  opening_random_moves: 1
  curriculum:
    sample_probability: 0.2
  adjudication_enabled: true
  adjudication_warmup_iters: 4
  adjudication_ramp_iters: 6
  adjudication_min_plies: 110
  adjudication_min_plies_init: 130
  adjudication_value_margin: 0.24
  adjudication_value_margin_init: 0.38
  adjudication_persist_plies: 10
  adjudication_persist_init: 12
  adjudication_material_margin: 5.0
  adjudication_material_margin_init: 7.5
  simulation_scale_min: 0.6
  simulation_scale_max: 0.95
  simulation_scale_buffer_target: 0.5

REPLAY:
  capacity: 32000

SAMPLING:
  recent_ratio: 0.6
  recent_ratio_min: 0.5
  recent_ratio_max: 0.7
  recent_window_frac: 0.3

RESIGN:
  enabled: true
  cooldown_iters: 4
  value_threshold: -0.40
  min_plies: 60
  consecutive_required: 2
  playthrough_fraction: 0.3

MCTS:
  train_simulations: 192
  train_simulations_min: 144
  train_sim_decay_move_interval: 40
  c_puct: 1.15
  c_puct_base: 19652
  c_puct_init: 1.5
  fpu_reduction: 0.12
  dirichlet_alpha: 0.25
  dirichlet_weight: 0.25
  visit_count_clamp: 65535

TRAIN:
  total_iterations: 12
  games_per_iter: 96
  games_per_iter_scale_min: 0.75
  games_per_iter_warmup_iters: 4
  batch_size: 128
  batch_size_min: 112
  batch_size_max: 144
  samples_per_new_game: 0.4
  update_steps_min: 20
  update_steps_max: 52
  learning_rate_init: 0.00065
  learning_rate_final: 0.0003
  learning_rate_warmup_steps: 720
  lr_steps_per_iter_estimate: 36
  lr_restart_interval_iters: 0
  lr_restart_decay: 1.0
  weight_decay: 0.00012
  momentum: 0.9
  grad_clip_norm: 1.0
  ema_enabled: true
  ema_decay: 0.999

ARENA:
  eval_every_iters: 4
  games_per_eval: 24
  mcts_simulations: 160
  temperature: 0.40
  temperature_moves: 10
  gate_baseline_p: 0.50
  gate_margin: 0.006
  gate_min_games: 20
  gate_min_decisive: 3
  gate_draw_weight: 0.5
  resign_enable: false
  max_game_plies: 160

LOG:
  checkpoint_interval_iters: 24
  empty_cache_interval_iters: 96
  metrics_csv_enable: true
