MODEL:
  blocks: 5
  channels: 88
TORCH:
  threads_intra: 12
  threads_inter: 2
SELFPLAY:
  num_workers: 4
  game_max_plies: 100
  temperature_moves: 36
  adjudication_enabled: true
  adjudication_min_plies: 64
  adjudication_value_margin: 0.12
  adjudication_persist_plies: 8
  opening_random_moves: 2
REPLAY:
  capacity: 21000
RESIGN:
  resign_enable: false
MCTS:
  train_simulations: 100
  train_simulations_min: 96
  train_sim_decay_move_interval: 24
TRAIN:
  total_iterations: 100
  games_per_iter: 100
  batch_size: 100
  batch_size_min: 96
  batch_size_max: 128
  samples_per_new_game: 0.55
  update_steps_min: 18
  update_steps_max: 44
  learning_rate_init: 0.0007
  learning_rate_final: 0.00032
ARENA:
  eval_every_iters: 16
  games_per_eval: 64
  mcts_simulations: 128
  temperature: 0.6
  temperature_moves: 20
  gate_margin: 0.005
  gate_min_decisive: 1
  resign_enable: false
  max_game_plies: 140
LOG:
  checkpoint_interval_iters: 24
  empty_cache_interval_iters: 96
RESIGN:
  min_plies: 32
  playthrough_fraction: 0.25
