from types import SimpleNamespace as _NS

SEED = 0


LOG = _NS(
    LEVEL="INFO",
    CUDA_EMPTY_CACHE_EVERY_ITERS=120,
    CHECKPOINT_SAVE_EVERY_ITERS=16,
    CHECKPOINT_FILE_PATH="checkpoints/checkpoint.pt",
    BEST_MODEL_FILE_PATH="checkpoints/best_model.pt",
    METRICS_LOG_CSV_ENABLE=True,
    METRICS_LOG_CSV_PATH="logs/training_log.csv",
    ARENA_SAVE_PGN_ENABLE=True,
    ARENA_SAVE_PGN_ON_PROMOTION=True,
    ARENA_SAVE_PGN_SAMPLES_PER_ROUND=2,
    ARENA_PGN_DIR="logs",
)


TORCH = _NS(
    AMP_ENABLED=True,
    MATMUL_FLOAT32_PRECISION="high",
    THREADS_INTRA=1,
    THREADS_INTER=1,
    MODEL_CHANNELS_LAST=True,
    EVAL_MODEL_CHANNELS_LAST=True,
)


DATA = _NS(
    U8_SCALE=255.0,
    VALUE_I8_SCALE=127.0,
)


MODEL = _NS(
    BLOCKS=6,
    CHANNELS=128,
    VALUE_CONV_CHANNELS=16,
    VALUE_HIDDEN_DIM=384,
)


EVAL = _NS(
    COALESCE_MS=22,
    WORKER_JOIN_TIMEOUT_S=0.15,
    BATCH_SIZE_MAX=384,
    CACHE_USE_FP16=True,
    CACHE_CAPACITY=3_000,
    ARENA_CACHE_CAPACITY=2_000,
)


SELFPLAY = _NS(
    NUM_WORKERS=4,
    GAME_MAX_PLIES=260,
    TEMP_MOVES=24,
    TEMP_HIGH=1.25,
    TEMP_LOW=0.45,
    DETERMINISTIC_TEMP_EPS=0.02,
    OPENING_RANDOM_PLIES_MAX=12,
    COLOR_FLIP_PROB=0.50,
    REPETITION_NOISE_COUNT=3,
    REPETITION_NOISE_WINDOW=12,
    COLOR_BALANCE_TOLERANCE_PCT=5.0,
    COLOR_BALANCE_WINDOW_ITERS=8,
)

REPLAY = _NS(
    BUFFER_CAPACITY=50_000,
)

SAMPLING = _NS(
    REPLAY_SNAPSHOT_RECENT_WINDOW_FRAC=0.28,
    REPLAY_SNAPSHOT_RECENT_RATIO_DEFAULT=0.70,
    TRAIN_RECENT_SAMPLE_RATIO=0.70,
    TRAIN_RECENT_SAMPLE_RATIO_MIN=0.35,
    TRAIN_RECENT_SAMPLE_RATIO_MAX=0.70,
    TRAIN_RECENT_SAMPLE_BUFFER_DECAY_START=0.40,
    TRAIN_RECENT_SAMPLE_BUFFER_DECAY_END=0.85,
)

AUGMENT = _NS(
    MIRROR_PROB=0.50,
    ROT180_PROB=0.25,
    VFLIP_CS_PROB=0.25,
)


MCTS = _NS(
    TRAIN_SIMULATIONS_BASE=80,
    TRAIN_SIMULATIONS_MIN=32,
    TRAIN_SIM_DECAY_MOVE_INTERVAL=14,
    C_PUCT=1.35,
    C_PUCT_BASE=19652.0,
    C_PUCT_INIT=1.55,
    DIRICHLET_ALPHA=0.40,
    DIRICHLET_WEIGHT=0.35,
    FPU_REDUCTION=0.11,
    VISIT_COUNT_CLAMP=65535,
)


RESIGN = _NS(
    ENABLED=True,
    VALUE_THRESHOLD=-0.22,
    CONSECUTIVE_PLIES=2,
    CONSECUTIVE_MIN=1,
    PLAYTHROUGH_FRACTION=0.10,
    DISABLE_UNTIL_ITERS=6,
)


TRAIN = _NS(
    LR_INIT=1.2e-3,
    LR_WARMUP_STEPS=1_200,
    LR_FINAL=4.0e-4,
    LR_SCHED_STEPS_PER_ITER_EST=40,
    LR_SCHED_DRIFT_ADJUST_THRESHOLD=15.0,
    WEIGHT_DECAY=1.5e-4,
    MOMENTUM=0.9,
    GRAD_CLIP_NORM=1.40,
    LOSS_POLICY_WEIGHT=1.0,
    LOSS_VALUE_WEIGHT=0.95,
    LOSS_VALUE_WEIGHT_LATE=1.15,
    LOSS_VALUE_WEIGHT_SWITCH_ITER=80,
    LOSS_POLICY_LABEL_SMOOTH=0.02,
    LOSS_ENTROPY_COEF_INIT=2.5e-4,
    LOSS_ENTROPY_ANNEAL_ITERS=320,
    LOSS_ENTROPY_COEF_MIN=1.8e-4,
    EMA_ENABLED=True,
    EMA_DECAY=0.9995,
    TOTAL_ITERATIONS=360,
    GAMES_PER_ITER=64,
    TARGET_TRAIN_SAMPLES_PER_NEW=1.0,
    UPDATE_STEPS_MIN=24,
    UPDATE_STEPS_MAX=128,
    BATCH_SIZE_MIN=256,
    BATCH_SIZE_MAX=256,
    BATCH_SIZE=256,
    LR_RESTART_INTERVAL_ITERS=80,
    LR_RESTART_DECAY=0.90,
)


ARENA = _NS(
    MCTS_EVAL_SIMULATIONS=352,
    EVAL_EVERY_ITERS=8,
    GAMES_PER_EVAL=64,
    TEMPERATURE=0.60,
    TEMP_MOVES=20,
    DIRICHLET_WEIGHT=0.10,
    OPENING_RANDOM_PLIES_MAX=18,
    OPENING_TEMPERATURE_EPS=1e-6,
    DRAW_SCORE=0.50,
    GATE_DRAW_WEIGHT=0.50,
    GATE_BASELINE_P=0.495,
    GATE_BASELINE_MARGIN=0.01,
    GATE_Z_EARLY=0.75,
    GATE_Z_LATE=1.10,
    GATE_Z_SWITCH_ITER=220,
    GATE_MIN_GAMES=60,
    GATE_DECISIVE_SECONDARY=True,
    GATE_MIN_DECISIVES=8,
    GATE_FORCE_DECISIVE=True,
    GAME_MAX_PLIES=260,
    RESIGN_ENABLE=True,
    RESIGN_CONSECUTIVE=2,
    RESIGN_VALUE_THRESHOLD=-0.22,
    RESIGN_PLAYTHROUGH_FRACTION=0.10,
    CANDIDATE_MAX_ROUNDS=4,
    CANDIDATE_MAX_GAMES=160,
    PAIRING_FACTOR=2,
    GATE_EPS=1e-9,
    GATE_MIN_NATURAL_PCT=0.25,
)
